// Internal contract between the stateless API and the stateful session worker.
//
// It travels only on the private network (overlay on Swarm, bridge on Compose).
// The API dials the grpc_addr registered in the lease, never a load-balanced
// VIP: the destination must be the exact process that owns the session.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: session/v1/session.proto

package sessionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionService_Connect_FullMethodName                      = "/zappermeow.session.v1.SessionService/Connect"
	SessionService_PairPhone_FullMethodName                    = "/zappermeow.session.v1.SessionService/PairPhone"
	SessionService_Disconnect_FullMethodName                   = "/zappermeow.session.v1.SessionService/Disconnect"
	SessionService_Logout_FullMethodName                       = "/zappermeow.session.v1.SessionService/Logout"
	SessionService_GetStatus_FullMethodName                    = "/zappermeow.session.v1.SessionService/GetStatus"
	SessionService_ApplySettings_FullMethodName                = "/zappermeow.session.v1.SessionService/ApplySettings"
	SessionService_SubmitPasskeyResponse_FullMethodName        = "/zappermeow.session.v1.SessionService/SubmitPasskeyResponse"
	SessionService_ConfirmPasskey_FullMethodName               = "/zappermeow.session.v1.SessionService/ConfirmPasskey"
	SessionService_GetIdentityVerificationCodes_FullMethodName = "/zappermeow.session.v1.SessionService/GetIdentityVerificationCodes"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	// Brings the session up: pairs when there is no device material, reconnects
	// when there is.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Starts a phone-code pairing attempt and returns the code to type on the
	// handset.
	PairPhone(ctx context.Context, in *PairPhoneRequest, opts ...grpc.CallOption) (*PairPhoneResponse, error)
	// Takes the session offline while keeping the device material.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Ends the session on WhatsApp, removes the companion device and deletes the
	// local material.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Live view held by the owner; complements the persisted state.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Reapplies the instance's persisted settings on the live session. The
	// request only says what changed: the worker rereads the values from
	// Postgres, so there is no window where the call and the database disagree.
	ApplySettings(ctx context.Context, in *ApplySettingsRequest, opts ...grpc.CallOption) (*ApplySettingsResponse, error)
	// Forwards the authenticator's WebAuthn assertion for the pending passkey
	// challenge of the pairing attempt in flight.
	SubmitPasskeyResponse(ctx context.Context, in *SubmitPasskeyResponseRequest, opts ...grpc.CallOption) (*SubmitPasskeyResponseResponse, error)
	// Confirms the handoff code that was shown to the number's owner.
	ConfirmPasskey(ctx context.Context, in *ConfirmPasskeyRequest, opts ...grpc.CallOption) (*ConfirmPasskeyResponse, error)
	// Identity verification codes (safety numbers) for a conversation with one
	// contact. Requires a connected session: it talks to WhatsApp.
	GetIdentityVerificationCodes(ctx context.Context, in *GetIdentityVerificationCodesRequest, opts ...grpc.CallOption) (*GetIdentityVerificationCodesResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, SessionService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) PairPhone(ctx context.Context, in *PairPhoneRequest, opts ...grpc.CallOption) (*PairPhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairPhoneResponse)
	err := c.cc.Invoke(ctx, SessionService_PairPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, SessionService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, SessionService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, SessionService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ApplySettings(ctx context.Context, in *ApplySettingsRequest, opts ...grpc.CallOption) (*ApplySettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySettingsResponse)
	err := c.cc.Invoke(ctx, SessionService_ApplySettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) SubmitPasskeyResponse(ctx context.Context, in *SubmitPasskeyResponseRequest, opts ...grpc.CallOption) (*SubmitPasskeyResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPasskeyResponseResponse)
	err := c.cc.Invoke(ctx, SessionService_SubmitPasskeyResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ConfirmPasskey(ctx context.Context, in *ConfirmPasskeyRequest, opts ...grpc.CallOption) (*ConfirmPasskeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPasskeyResponse)
	err := c.cc.Invoke(ctx, SessionService_ConfirmPasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetIdentityVerificationCodes(ctx context.Context, in *GetIdentityVerificationCodesRequest, opts ...grpc.CallOption) (*GetIdentityVerificationCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityVerificationCodesResponse)
	err := c.cc.Invoke(ctx, SessionService_GetIdentityVerificationCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
type SessionServiceServer interface {
	// Brings the session up: pairs when there is no device material, reconnects
	// when there is.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Starts a phone-code pairing attempt and returns the code to type on the
	// handset.
	PairPhone(context.Context, *PairPhoneRequest) (*PairPhoneResponse, error)
	// Takes the session offline while keeping the device material.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Ends the session on WhatsApp, removes the companion device and deletes the
	// local material.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Live view held by the owner; complements the persisted state.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Reapplies the instance's persisted settings on the live session. The
	// request only says what changed: the worker rereads the values from
	// Postgres, so there is no window where the call and the database disagree.
	ApplySettings(context.Context, *ApplySettingsRequest) (*ApplySettingsResponse, error)
	// Forwards the authenticator's WebAuthn assertion for the pending passkey
	// challenge of the pairing attempt in flight.
	SubmitPasskeyResponse(context.Context, *SubmitPasskeyResponseRequest) (*SubmitPasskeyResponseResponse, error)
	// Confirms the handoff code that was shown to the number's owner.
	ConfirmPasskey(context.Context, *ConfirmPasskeyRequest) (*ConfirmPasskeyResponse, error)
	// Identity verification codes (safety numbers) for a conversation with one
	// contact. Requires a connected session: it talks to WhatsApp.
	GetIdentityVerificationCodes(context.Context, *GetIdentityVerificationCodesRequest) (*GetIdentityVerificationCodesResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSessionServiceServer) PairPhone(context.Context, *PairPhoneRequest) (*PairPhoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PairPhone not implemented")
}
func (UnimplementedSessionServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedSessionServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedSessionServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSessionServiceServer) ApplySettings(context.Context, *ApplySettingsRequest) (*ApplySettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySettings not implemented")
}
func (UnimplementedSessionServiceServer) SubmitPasskeyResponse(context.Context, *SubmitPasskeyResponseRequest) (*SubmitPasskeyResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPasskeyResponse not implemented")
}
func (UnimplementedSessionServiceServer) ConfirmPasskey(context.Context, *ConfirmPasskeyRequest) (*ConfirmPasskeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPasskey not implemented")
}
func (UnimplementedSessionServiceServer) GetIdentityVerificationCodes(context.Context, *GetIdentityVerificationCodesRequest) (*GetIdentityVerificationCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityVerificationCodes not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_PairPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).PairPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_PairPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).PairPhone(ctx, req.(*PairPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ApplySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ApplySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ApplySettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ApplySettings(ctx, req.(*ApplySettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_SubmitPasskeyResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPasskeyResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SubmitPasskeyResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_SubmitPasskeyResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SubmitPasskeyResponse(ctx, req.(*SubmitPasskeyResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ConfirmPasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ConfirmPasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ConfirmPasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ConfirmPasskey(ctx, req.(*ConfirmPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetIdentityVerificationCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityVerificationCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetIdentityVerificationCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetIdentityVerificationCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetIdentityVerificationCodes(ctx, req.(*GetIdentityVerificationCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zappermeow.session.v1.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _SessionService_Connect_Handler,
		},
		{
			MethodName: "PairPhone",
			Handler:    _SessionService_PairPhone_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _SessionService_Disconnect_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _SessionService_Logout_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SessionService_GetStatus_Handler,
		},
		{
			MethodName: "ApplySettings",
			Handler:    _SessionService_ApplySettings_Handler,
		},
		{
			MethodName: "SubmitPasskeyResponse",
			Handler:    _SessionService_SubmitPasskeyResponse_Handler,
		},
		{
			MethodName: "ConfirmPasskey",
			Handler:    _SessionService_ConfirmPasskey_Handler,
		},
		{
			MethodName: "GetIdentityVerificationCodes",
			Handler:    _SessionService_GetIdentityVerificationCodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session/v1/session.proto",
}
