// Internal contract between the stateless API and the stateful session worker.
//
// It travels only on the private network (overlay on Swarm, bridge on Compose).
// The API dials the grpc_addr registered in the lease, never a load-balanced
// VIP: the destination must be the exact process that owns the session.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: session/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED  SessionState = 0
	SessionState_SESSION_STATE_REGISTERED   SessionState = 1
	SessionState_SESSION_STATE_PAIRING      SessionState = 2
	SessionState_SESSION_STATE_CONNECTING   SessionState = 3
	SessionState_SESSION_STATE_CONNECTED    SessionState = 4
	SessionState_SESSION_STATE_DISCONNECTED SessionState = 5
	SessionState_SESSION_STATE_LOGGED_OUT   SessionState = 6
	SessionState_SESSION_STATE_BANNED       SessionState = 7
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_REGISTERED",
		2: "SESSION_STATE_PAIRING",
		3: "SESSION_STATE_CONNECTING",
		4: "SESSION_STATE_CONNECTED",
		5: "SESSION_STATE_DISCONNECTED",
		6: "SESSION_STATE_LOGGED_OUT",
		7: "SESSION_STATE_BANNED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED":  0,
		"SESSION_STATE_REGISTERED":   1,
		"SESSION_STATE_PAIRING":      2,
		"SESSION_STATE_CONNECTING":   3,
		"SESSION_STATE_CONNECTED":    4,
		"SESSION_STATE_DISCONNECTED": 5,
		"SESSION_STATE_LOGGED_OUT":   6,
		"SESSION_STATE_BANNED":       7,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_session_v1_session_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_session_v1_session_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{0}
}

type PairingMethod int32

const (
	PairingMethod_PAIRING_METHOD_UNSPECIFIED PairingMethod = 0
	PairingMethod_PAIRING_METHOD_QR          PairingMethod = 1
	PairingMethod_PAIRING_METHOD_PHONE       PairingMethod = 2
)

// Enum value maps for PairingMethod.
var (
	PairingMethod_name = map[int32]string{
		0: "PAIRING_METHOD_UNSPECIFIED",
		1: "PAIRING_METHOD_QR",
		2: "PAIRING_METHOD_PHONE",
	}
	PairingMethod_value = map[string]int32{
		"PAIRING_METHOD_UNSPECIFIED": 0,
		"PAIRING_METHOD_QR":          1,
		"PAIRING_METHOD_PHONE":       2,
	}
)

func (x PairingMethod) Enum() *PairingMethod {
	p := new(PairingMethod)
	*p = x
	return p
}

func (x PairingMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PairingMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_session_v1_session_proto_enumTypes[1].Descriptor()
}

func (PairingMethod) Type() protoreflect.EnumType {
	return &file_session_v1_session_proto_enumTypes[1]
}

func (x PairingMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PairingMethod.Descriptor instead.
func (PairingMethod) EnumDescriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{1}
}

// Fence carries the caller's view of who owns the session. The worker compares
// generation against the lease it holds and refuses anything stale, so a
// process that lost ownership can never act on the session.
type Fence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // UUID
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`                  // lease generation known to the API
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fence) Reset() {
	*x = Fence{}
	mi := &file_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fence) ProtoMessage() {}

func (x *Fence) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fence.ProtoReflect.Descriptor instead.
func (*Fence) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Fence) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Fence) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// DeviceIdentity is one companion device. The JID keeps its device suffix: that
// suffix is what distinguishes two instances paired to the same phone number.
type DeviceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Lid           string                 `protobuf:"bytes,2,opt,name=lid,proto3" json:"lid,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PushName      string                 `protobuf:"bytes,4,opt,name=push_name,json=pushName,proto3" json:"push_name,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	BusinessName  string                 `protobuf:"bytes,6,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIdentity) Reset() {
	*x = DeviceIdentity{}
	mi := &file_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdentity) ProtoMessage() {}

func (x *DeviceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdentity.ProtoReflect.Descriptor instead.
func (*DeviceIdentity) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceIdentity) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *DeviceIdentity) GetLid() string {
	if x != nil {
		return x.Lid
	}
	return ""
}

func (x *DeviceIdentity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DeviceIdentity) GetPushName() string {
	if x != nil {
		return x.PushName
	}
	return ""
}

func (x *DeviceIdentity) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceIdentity) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_session_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type ConnectResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	State            SessionState           `protobuf:"varint,1,opt,name=state,proto3,enum=zappermeow.session.v1.SessionState" json:"state,omitempty"`
	PairingStarted   bool                   `protobuf:"varint,2,opt,name=pairing_started,json=pairingStarted,proto3" json:"pairing_started,omitempty"`
	PairingExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=pairing_expires_at,json=pairingExpiresAt,proto3" json:"pairing_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_session_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *ConnectResponse) GetPairingStarted() bool {
	if x != nil {
		return x.PairingStarted
	}
	return false
}

func (x *ConnectResponse) GetPairingExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PairingExpiresAt
	}
	return nil
}

type PairPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`        // E.164 without '+'
	ReplaceActive bool                   `protobuf:"varint,3,opt,name=replace_active,json=replaceActive,proto3" json:"replace_active,omitempty"` // ends an attempt already in flight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairPhoneRequest) Reset() {
	*x = PairPhoneRequest{}
	mi := &file_session_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairPhoneRequest) ProtoMessage() {}

func (x *PairPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairPhoneRequest.ProtoReflect.Descriptor instead.
func (*PairPhoneRequest) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *PairPhoneRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *PairPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PairPhoneRequest) GetReplaceActive() bool {
	if x != nil {
		return x.ReplaceActive
	}
	return false
}

type PairPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairingCode   string                 `protobuf:"bytes,1,opt,name=pairing_code,json=pairingCode,proto3" json:"pairing_code,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairPhoneResponse) Reset() {
	*x = PairPhoneResponse{}
	mi := &file_session_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairPhoneResponse) ProtoMessage() {}

func (x *PairPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairPhoneResponse.ProtoReflect.Descriptor instead.
func (*PairPhoneResponse) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *PairPhoneResponse) GetPairingCode() string {
	if x != nil {
		return x.PairingCode
	}
	return ""
}

func (x *PairPhoneResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_session_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SessionState           `protobuf:"varint,1,opt,name=state,proto3,enum=zappermeow.session.v1.SessionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_session_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *DisconnectResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Fence *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	// Allows connecting briefly to remove the device on the server before
	// deleting the local material.
	AllowTemporaryConnect bool `protobuf:"varint,2,opt,name=allow_temporary_connect,json=allowTemporaryConnect,proto3" json:"allow_temporary_connect,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_session_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

func (x *LogoutRequest) GetAllowTemporaryConnect() bool {
	if x != nil {
		return x.AllowTemporaryConnect
	}
	return false
}

type LogoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State SessionState           `protobuf:"varint,1,opt,name=state,proto3,enum=zappermeow.session.v1.SessionState" json:"state,omitempty"`
	// false means only the local material was deleted: the device may still be
	// listed on the customer's handset.
	RemoteRemoved bool `protobuf:"varint,2,opt,name=remote_removed,json=remoteRemoved,proto3" json:"remote_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_session_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *LogoutResponse) GetRemoteRemoved() bool {
	if x != nil {
		return x.RemoteRemoved
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fence         *Fence                 `protobuf:"bytes,1,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_session_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatusRequest) GetFence() *Fence {
	if x != nil {
		return x.Fence
	}
	return nil
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SessionState           `protobuf:"varint,1,opt,name=state,proto3,enum=zappermeow.session.v1.SessionState" json:"state,omitempty"`
	Device        *DeviceIdentity        `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	LoggedIn      bool                   `protobuf:"varint,4,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	PairingMethod PairingMethod          `protobuf:"varint,5,opt,name=pairing_method,json=pairingMethod,proto3,enum=zappermeow.session.v1.PairingMethod" json:"pairing_method,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_session_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_session_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetDevice() *DeviceIdentity {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *GetStatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GetStatusResponse) GetLoggedIn() bool {
	if x != nil {
		return x.LoggedIn
	}
	return false
}

func (x *GetStatusResponse) GetPairingMethod() PairingMethod {
	if x != nil {
		return x.PairingMethod
	}
	return PairingMethod_PAIRING_METHOD_UNSPECIFIED
}

func (x *GetStatusResponse) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

var File_session_v1_session_proto protoreflect.FileDescriptor

const file_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x18session/v1/session.proto\x12\x15zappermeow.session.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x05Fence\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\"\xb5\x01\n" +
	"\x0eDeviceIdentity\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x10\n" +
	"\x03lid\x18\x02 \x01(\tR\x03lid\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\tpush_name\x18\x04 \x01(\tR\bpushName\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12#\n" +
	"\rbusiness_name\x18\x06 \x01(\tR\fbusinessName\"D\n" +
	"\x0eConnectRequest\x122\n" +
	"\x05fence\x18\x01 \x01(\v2\x1c.zappermeow.session.v1.FenceR\x05fence\"\xbf\x01\n" +
	"\x0fConnectResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.zappermeow.session.v1.SessionStateR\x05state\x12'\n" +
	"\x0fpairing_started\x18\x02 \x01(\bR\x0epairingStarted\x12H\n" +
	"\x12pairing_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10pairingExpiresAt\"\x90\x01\n" +
	"\x10PairPhoneRequest\x122\n" +
	"\x05fence\x18\x01 \x01(\v2\x1c.zappermeow.session.v1.FenceR\x05fence\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12%\n" +
	"\x0ereplace_active\x18\x03 \x01(\bR\rreplaceActive\"q\n" +
	"\x11PairPhoneResponse\x12!\n" +
	"\fpairing_code\x18\x01 \x01(\tR\vpairingCode\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"G\n" +
	"\x11DisconnectRequest\x122\n" +
	"\x05fence\x18\x01 \x01(\v2\x1c.zappermeow.session.v1.FenceR\x05fence\"O\n" +
	"\x12DisconnectResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.zappermeow.session.v1.SessionStateR\x05state\"{\n" +
	"\rLogoutRequest\x122\n" +
	"\x05fence\x18\x01 \x01(\v2\x1c.zappermeow.session.v1.FenceR\x05fence\x126\n" +
	"\x17allow_temporary_connect\x18\x02 \x01(\bR\x15allowTemporaryConnect\"r\n" +
	"\x0eLogoutResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.zappermeow.session.v1.SessionStateR\x05state\x12%\n" +
	"\x0eremote_removed\x18\x02 \x01(\bR\rremoteRemoved\"F\n" +
	"\x10GetStatusRequest\x122\n" +
	"\x05fence\x18\x01 \x01(\v2\x1c.zappermeow.session.v1.FenceR\x05fence\"\xd4\x02\n" +
	"\x11GetStatusResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.zappermeow.session.v1.SessionStateR\x05state\x12=\n" +
	"\x06device\x18\x02 \x01(\v2%.zappermeow.session.v1.DeviceIdentityR\x06device\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12\x1b\n" +
	"\tlogged_in\x18\x04 \x01(\bR\bloggedIn\x12K\n" +
	"\x0epairing_method\x18\x05 \x01(\x0e2$.zappermeow.session.v1.PairingMethodR\rpairingMethod\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt*\xf9\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SESSION_STATE_REGISTERED\x10\x01\x12\x19\n" +
	"\x15SESSION_STATE_PAIRING\x10\x02\x12\x1c\n" +
	"\x18SESSION_STATE_CONNECTING\x10\x03\x12\x1b\n" +
	"\x17SESSION_STATE_CONNECTED\x10\x04\x12\x1e\n" +
	"\x1aSESSION_STATE_DISCONNECTED\x10\x05\x12\x1c\n" +
	"\x18SESSION_STATE_LOGGED_OUT\x10\x06\x12\x18\n" +
	"\x14SESSION_STATE_BANNED\x10\a*`\n" +
	"\rPairingMethod\x12\x1e\n" +
	"\x1aPAIRING_METHOD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PAIRING_METHOD_QR\x10\x01\x12\x18\n" +
	"\x14PAIRING_METHOD_PHONE\x10\x022\xe4\x03\n" +
	"\x0eSessionService\x12X\n" +
	"\aConnect\x12%.zappermeow.session.v1.ConnectRequest\x1a&.zappermeow.session.v1.ConnectResponse\x12^\n" +
	"\tPairPhone\x12'.zappermeow.session.v1.PairPhoneRequest\x1a(.zappermeow.session.v1.PairPhoneResponse\x12a\n" +
	"\n" +
	"Disconnect\x12(.zappermeow.session.v1.DisconnectRequest\x1a).zappermeow.session.v1.DisconnectResponse\x12U\n" +
	"\x06Logout\x12$.zappermeow.session.v1.LogoutRequest\x1a%.zappermeow.session.v1.LogoutResponse\x12^\n" +
	"\tGetStatus\x12'.zappermeow.session.v1.GetStatusRequest\x1a(.zappermeow.session.v1.GetStatusResponseBAZ?github.com/zapperhub/zappermeow/internal/pb/sessionv1;sessionv1b\x06proto3"

var (
	file_session_v1_session_proto_rawDescOnce sync.Once
	file_session_v1_session_proto_rawDescData []byte
)

func file_session_v1_session_proto_rawDescGZIP() []byte {
	file_session_v1_session_proto_rawDescOnce.Do(func() {
		file_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_v1_session_proto_rawDesc), len(file_session_v1_session_proto_rawDesc)))
	})
	return file_session_v1_session_proto_rawDescData
}

var file_session_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_session_v1_session_proto_goTypes = []any{
	(SessionState)(0),             // 0: zappermeow.session.v1.SessionState
	(PairingMethod)(0),            // 1: zappermeow.session.v1.PairingMethod
	(*Fence)(nil),                 // 2: zappermeow.session.v1.Fence
	(*DeviceIdentity)(nil),        // 3: zappermeow.session.v1.DeviceIdentity
	(*ConnectRequest)(nil),        // 4: zappermeow.session.v1.ConnectRequest
	(*ConnectResponse)(nil),       // 5: zappermeow.session.v1.ConnectResponse
	(*PairPhoneRequest)(nil),      // 6: zappermeow.session.v1.PairPhoneRequest
	(*PairPhoneResponse)(nil),     // 7: zappermeow.session.v1.PairPhoneResponse
	(*DisconnectRequest)(nil),     // 8: zappermeow.session.v1.DisconnectRequest
	(*DisconnectResponse)(nil),    // 9: zappermeow.session.v1.DisconnectResponse
	(*LogoutRequest)(nil),         // 10: zappermeow.session.v1.LogoutRequest
	(*LogoutResponse)(nil),        // 11: zappermeow.session.v1.LogoutResponse
	(*GetStatusRequest)(nil),      // 12: zappermeow.session.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 13: zappermeow.session.v1.GetStatusResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_session_v1_session_proto_depIdxs = []int32{
	2,  // 0: zappermeow.session.v1.ConnectRequest.fence:type_name -> zappermeow.session.v1.Fence
	0,  // 1: zappermeow.session.v1.ConnectResponse.state:type_name -> zappermeow.session.v1.SessionState
	14, // 2: zappermeow.session.v1.ConnectResponse.pairing_expires_at:type_name -> google.protobuf.Timestamp
	2,  // 3: zappermeow.session.v1.PairPhoneRequest.fence:type_name -> zappermeow.session.v1.Fence
	14, // 4: zappermeow.session.v1.PairPhoneResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 5: zappermeow.session.v1.DisconnectRequest.fence:type_name -> zappermeow.session.v1.Fence
	0,  // 6: zappermeow.session.v1.DisconnectResponse.state:type_name -> zappermeow.session.v1.SessionState
	2,  // 7: zappermeow.session.v1.LogoutRequest.fence:type_name -> zappermeow.session.v1.Fence
	0,  // 8: zappermeow.session.v1.LogoutResponse.state:type_name -> zappermeow.session.v1.SessionState
	2,  // 9: zappermeow.session.v1.GetStatusRequest.fence:type_name -> zappermeow.session.v1.Fence
	0,  // 10: zappermeow.session.v1.GetStatusResponse.state:type_name -> zappermeow.session.v1.SessionState
	3,  // 11: zappermeow.session.v1.GetStatusResponse.device:type_name -> zappermeow.session.v1.DeviceIdentity
	1,  // 12: zappermeow.session.v1.GetStatusResponse.pairing_method:type_name -> zappermeow.session.v1.PairingMethod
	14, // 13: zappermeow.session.v1.GetStatusResponse.connected_at:type_name -> google.protobuf.Timestamp
	4,  // 14: zappermeow.session.v1.SessionService.Connect:input_type -> zappermeow.session.v1.ConnectRequest
	6,  // 15: zappermeow.session.v1.SessionService.PairPhone:input_type -> zappermeow.session.v1.PairPhoneRequest
	8,  // 16: zappermeow.session.v1.SessionService.Disconnect:input_type -> zappermeow.session.v1.DisconnectRequest
	10, // 17: zappermeow.session.v1.SessionService.Logout:input_type -> zappermeow.session.v1.LogoutRequest
	12, // 18: zappermeow.session.v1.SessionService.GetStatus:input_type -> zappermeow.session.v1.GetStatusRequest
	5,  // 19: zappermeow.session.v1.SessionService.Connect:output_type -> zappermeow.session.v1.ConnectResponse
	7,  // 20: zappermeow.session.v1.SessionService.PairPhone:output_type -> zappermeow.session.v1.PairPhoneResponse
	9,  // 21: zappermeow.session.v1.SessionService.Disconnect:output_type -> zappermeow.session.v1.DisconnectResponse
	11, // 22: zappermeow.session.v1.SessionService.Logout:output_type -> zappermeow.session.v1.LogoutResponse
	13, // 23: zappermeow.session.v1.SessionService.GetStatus:output_type -> zappermeow.session.v1.GetStatusResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_session_v1_session_proto_init() }
func file_session_v1_session_proto_init() {
	if File_session_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_v1_session_proto_rawDesc), len(file_session_v1_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_v1_session_proto_goTypes,
		DependencyIndexes: file_session_v1_session_proto_depIdxs,
		EnumInfos:         file_session_v1_session_proto_enumTypes,
		MessageInfos:      file_session_v1_session_proto_msgTypes,
	}.Build()
	File_session_v1_session_proto = out.File
	file_session_v1_session_proto_goTypes = nil
	file_session_v1_session_proto_depIdxs = nil
}
