// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT count(*) FROM api_keys WHERE status = 'active'
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, instance_id, label, key_prefix, secret_hash, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'active', now())
RETURNING id, instance_id, label, key_prefix, status, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Label      *string
	KeyPrefix  string
	SecretHash []byte
}

type CreateAPIKeyRow struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Label      *string
	KeyPrefix  string
	Status     string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.InstanceID,
		arg.Label,
		arg.KeyPrefix,
		arg.SecretHash,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Label,
		&i.KeyPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getKeyForAuth = `-- name: GetKeyForAuth :one
SELECT k.id AS key_id, k.instance_id, k.label, k.key_prefix, k.status AS key_status,
       i.name AS instance_name, i.connection_state AS instance_state,
       t.id AS tenant_id, t.status AS tenant_status
FROM api_keys k
JOIN instances i ON i.id = k.instance_id
JOIN tenants t ON t.id = i.tenant_id
WHERE k.secret_hash = $1
`

type GetKeyForAuthRow struct {
	KeyID         uuid.UUID
	InstanceID    uuid.UUID
	Label         *string
	KeyPrefix     string
	KeyStatus     string
	InstanceName  string
	InstanceState string
	TenantID      uuid.UUID
	TenantStatus  string
}

// The whole operational authorisation chain in a single indexed lookup on the
// unique secret_hash: the key, the instance it belongs to and the status of the
// owning tenant. Status columns come back raw so the caller can tell "revoked"
// apart from "wrong instance" apart from "suspended tenant".
func (q *Queries) GetKeyForAuth(ctx context.Context, secretHash []byte) (GetKeyForAuthRow, error) {
	row := q.db.QueryRow(ctx, getKeyForAuth, secretHash)
	var i GetKeyForAuthRow
	err := row.Scan(
		&i.KeyID,
		&i.InstanceID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyStatus,
		&i.InstanceName,
		&i.InstanceState,
		&i.TenantID,
		&i.TenantStatus,
	)
	return i, err
}

const listKeysByInstance = `-- name: ListKeysByInstance :many
SELECT id, instance_id, label, key_prefix, status, created_at, revoked_at
FROM api_keys
WHERE instance_id = $1
ORDER BY created_at
`

type ListKeysByInstanceRow struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Label      *string
	KeyPrefix  string
	Status     string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

// Never selects secret_hash: a listing has no business touching credential
// material, and the full secret is unrecoverable by design (FR-011).
func (q *Queries) ListKeysByInstance(ctx context.Context, instanceID uuid.UUID) ([]ListKeysByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listKeysByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeysByInstanceRow{}
	for rows.Next() {
		var i ListKeysByInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Label,
			&i.KeyPrefix,
			&i.Status,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys k
SET status = 'revoked', revoked_at = COALESCE(k.revoked_at, now())
FROM instances i
WHERE k.id = $1
  AND k.instance_id = i.id
  AND i.id = $2
  AND i.tenant_id = $3
RETURNING k.id, k.instance_id, k.label, k.key_prefix, k.status, k.created_at, k.revoked_at
`

type RevokeAPIKeyParams struct {
	ID       uuid.UUID
	ID_2     uuid.UUID
	TenantID uuid.UUID
}

type RevokeAPIKeyRow struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Label      *string
	KeyPrefix  string
	Status     string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

// Scoped through the instance to the tenant, so a key of another tenant cannot
// be revoked. Revocation is one-way and idempotent on an already revoked key.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ID_2, arg.TenantID)
	var i RevokeAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Label,
		&i.KeyPrefix,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
