// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const clearDeviceIdentity = `-- name: ClearDeviceIdentity :exec
UPDATE instances
SET wa_jid = NULL,
    wa_lid = NULL,
    phone_number = NULL,
    push_name = NULL,
    platform = NULL,
    business_name = NULL,
    paired_at = NULL,
    connected_at = NULL,
    ban_expires_at = NULL,
    connection_state = 'registered',
    updated_at = now()
WHERE id = $1
`

// Logout drops the identity but the trail keeps the history of what was paired.
func (q *Queries) ClearDeviceIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDeviceIdentity, id)
	return err
}

const clearDeviceMaterial = `-- name: ClearDeviceMaterial :exec
UPDATE instances
SET wa_jid = NULL,
    wa_lid = NULL,
    push_name = NULL,
    platform = NULL,
    business_name = NULL,
    paired_at = NULL,
    connected_at = NULL,
    updated_at = now()
WHERE id = $1
`

// Drops the device identity while leaving the connection state alone.
// A remote logout destroys the material on both sides, so the row must stop
// pointing at it — otherwise the next connect loads nothing and the instance
// can never be paired again.
func (q *Queries) ClearDeviceMaterial(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDeviceMaterial, id)
	return err
}

const getInstanceConnection = `-- name: GetInstanceConnection :one
SELECT id, tenant_id, name, connection_state, created_at, updated_at, connection_intent, wa_jid, wa_lid, phone_number, push_name, platform, business_name, paired_at, connected_at, last_disconnect_at, last_disconnect_reason, ban_expires_at, proxy_url, passive_mode FROM instances WHERE id = $1 AND tenant_id = $2
`

type GetInstanceConnectionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetInstanceConnection(ctx context.Context, arg GetInstanceConnectionParams) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceConnection, arg.ID, arg.TenantID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ConnectionState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionIntent,
		&i.WaJid,
		&i.WaLid,
		&i.PhoneNumber,
		&i.PushName,
		&i.Platform,
		&i.BusinessName,
		&i.PairedAt,
		&i.ConnectedAt,
		&i.LastDisconnectAt,
		&i.LastDisconnectReason,
		&i.BanExpiresAt,
		&i.ProxyUrl,
		&i.PassiveMode,
	)
	return i, err
}

const getInstanceConnectionByID = `-- name: GetInstanceConnectionByID :one
SELECT id, tenant_id, name, connection_state, created_at, updated_at, connection_intent, wa_jid, wa_lid, phone_number, push_name, platform, business_name, paired_at, connected_at, last_disconnect_at, last_disconnect_reason, ban_expires_at, proxy_url, passive_mode FROM instances WHERE id = $1
`

// Worker-side lookup: the owner acts on an instance it holds a lease for, and
// the lease is already scoped to a single instance.
func (q *Queries) GetInstanceConnectionByID(ctx context.Context, id uuid.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceConnectionByID, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ConnectionState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionIntent,
		&i.WaJid,
		&i.WaLid,
		&i.PhoneNumber,
		&i.PushName,
		&i.Platform,
		&i.BusinessName,
		&i.PairedAt,
		&i.ConnectedAt,
		&i.LastDisconnectAt,
		&i.LastDisconnectReason,
		&i.BanExpiresAt,
		&i.ProxyUrl,
		&i.PassiveMode,
	)
	return i, err
}

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT proxy_url, passive_mode FROM instances WHERE id = $1
`

type GetInstanceSettingsRow struct {
	ProxyUrl    *string
	PassiveMode bool
}

// What the worker rereads when told settings changed. Keeping the read here,
// rather than shipping the values over gRPC, removes the window where the
// command and the database could disagree.
func (q *Queries) GetInstanceSettings(ctx context.Context, id uuid.UUID) (GetInstanceSettingsRow, error) {
	row := q.db.QueryRow(ctx, getInstanceSettings, id)
	var i GetInstanceSettingsRow
	err := row.Scan(&i.ProxyUrl, &i.PassiveMode)
	return i, err
}

const listActiveIntentInstancesByTenant = `-- name: ListActiveIntentInstancesByTenant :many
SELECT id FROM instances WHERE tenant_id = $1 AND connection_intent = 'active'
`

// Instances the tenant had asked to keep online. Reactivation restores these
// and nothing else, so an instance the user had disconnected stays down.
func (q *Queries) ListActiveIntentInstancesByTenant(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveIntentInstancesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceIDsByTenant = `-- name: ListInstanceIDsByTenant :many
SELECT id FROM instances WHERE tenant_id = $1
`

func (q *Queries) ListInstanceIDsByTenant(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listInstanceIDsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesSharingNumber = `-- name: ListInstancesSharingNumber :many
SELECT id FROM instances
WHERE tenant_id = $1 AND phone_number = $2 AND id <> $3
ORDER BY created_at
`

type ListInstancesSharingNumberParams struct {
	TenantID    uuid.UUID
	PhoneNumber *string
	ID          uuid.UUID
}

// Same number, same tenant, different instance: legitimate companion devices,
// surfaced as context and never as a conflict (FR-018).
func (q *Queries) ListInstancesSharingNumber(ctx context.Context, arg ListInstancesSharingNumberParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listInstancesSharingNumber, arg.TenantID, arg.PhoneNumber, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDisconnect = `-- name: RecordDisconnect :exec
UPDATE instances
SET connection_state = $2,
    connected_at = NULL,
    last_disconnect_at = now(),
    last_disconnect_reason = $3,
    ban_expires_at = $4,
    updated_at = now()
WHERE id = $1
`

type RecordDisconnectParams struct {
	ID                   uuid.UUID
	ConnectionState      string
	LastDisconnectReason *string
	BanExpiresAt         *time.Time
}

func (q *Queries) RecordDisconnect(ctx context.Context, arg RecordDisconnectParams) error {
	_, err := q.db.Exec(ctx, recordDisconnect,
		arg.ID,
		arg.ConnectionState,
		arg.LastDisconnectReason,
		arg.BanExpiresAt,
	)
	return err
}

const setConnectionIntent = `-- name: SetConnectionIntent :one

UPDATE instances
SET connection_intent = $2,
    last_disconnect_reason = CASE WHEN $3::boolean THEN NULL ELSE last_disconnect_reason END,
    updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, connection_state, created_at, updated_at, connection_intent, wa_jid, wa_lid, phone_number, push_name, platform, business_name, paired_at, connected_at, last_disconnect_at, last_disconnect_reason, ban_expires_at, proxy_url, passive_mode
`

type SetConnectionIntentParams struct {
	ID               uuid.UUID
	ConnectionIntent string
	ClearReason      bool
}

// Connection state of an instance. Statements that a tenant can reach filter by
// tenant_id in SQL, so a query can never be reused in a way that crosses tenants.
// The user's wish, changed only by an explicit command. Clearing
// last_disconnect_reason is what re-enables automatic adoption after an
// invalidation (FR-031), so it happens here and nowhere else.
func (q *Queries) SetConnectionIntent(ctx context.Context, arg SetConnectionIntentParams) (Instance, error) {
	row := q.db.QueryRow(ctx, setConnectionIntent, arg.ID, arg.ConnectionIntent, arg.ClearReason)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ConnectionState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConnectionIntent,
		&i.WaJid,
		&i.WaLid,
		&i.PhoneNumber,
		&i.PushName,
		&i.Platform,
		&i.BusinessName,
		&i.PairedAt,
		&i.ConnectedAt,
		&i.LastDisconnectAt,
		&i.LastDisconnectReason,
		&i.BanExpiresAt,
		&i.ProxyUrl,
		&i.PassiveMode,
	)
	return i, err
}

const setConnectionState = `-- name: SetConnectionState :exec
UPDATE instances
SET connection_state = $2,
    connected_at = CASE WHEN $2 = 'connected' THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
`

type SetConnectionStateParams struct {
	ID              uuid.UUID
	ConnectionState string
}

func (q *Queries) SetConnectionState(ctx context.Context, arg SetConnectionStateParams) error {
	_, err := q.db.Exec(ctx, setConnectionState, arg.ID, arg.ConnectionState)
	return err
}

const setDeviceIdentity = `-- name: SetDeviceIdentity :exec
UPDATE instances
SET wa_jid = $2,
    wa_lid = $3,
    phone_number = $4,
    push_name = $5,
    platform = $6,
    business_name = $7,
    paired_at = now(),
    updated_at = now()
WHERE id = $1
`

type SetDeviceIdentityParams struct {
	ID           uuid.UUID
	WaJid        *string
	WaLid        *string
	PhoneNumber  *string
	PushName     *string
	Platform     *string
	BusinessName *string
}

// Persists the paired companion device. The JID keeps its device suffix: it is
// what tells two instances of the same number apart.
func (q *Queries) SetDeviceIdentity(ctx context.Context, arg SetDeviceIdentityParams) error {
	_, err := q.db.Exec(ctx, setDeviceIdentity,
		arg.ID,
		arg.WaJid,
		arg.WaLid,
		arg.PhoneNumber,
		arg.PushName,
		arg.Platform,
		arg.BusinessName,
	)
	return err
}

const setInstancePassiveMode = `-- name: SetInstancePassiveMode :exec
UPDATE instances
SET passive_mode = $2,
    updated_at = now()
WHERE id = $1
`

type SetInstancePassiveModeParams struct {
	ID          uuid.UUID
	PassiveMode bool
}

func (q *Queries) SetInstancePassiveMode(ctx context.Context, arg SetInstancePassiveModeParams) error {
	_, err := q.db.Exec(ctx, setInstancePassiveMode, arg.ID, arg.PassiveMode)
	return err
}

const setInstanceProxy = `-- name: SetInstanceProxy :exec
UPDATE instances
SET proxy_url = $2,
    updated_at = now()
WHERE id = $1
`

type SetInstanceProxyParams struct {
	ID       uuid.UUID
	ProxyUrl *string
}

// The raw URL, credentials included. Only the worker reads it back to build a
// client; every path that faces a tenant masks it first.
func (q *Queries) SetInstanceProxy(ctx context.Context, arg SetInstanceProxyParams) error {
	_, err := q.db.Exec(ctx, setInstanceProxy, arg.ID, arg.ProxyUrl)
	return err
}
