// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection_events.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const advisoryUnlock = `-- name: AdvisoryUnlock :exec
SELECT pg_advisory_unlock($1)
`

func (q *Queries) AdvisoryUnlock(ctx context.Context, pgAdvisoryUnlock int64) error {
	_, err := q.db.Exec(ctx, advisoryUnlock, pgAdvisoryUnlock)
	return err
}

const appendConnectionEvent = `-- name: AppendConnectionEvent :one

INSERT INTO connection_events (instance_id, type, reason, detail)
VALUES ($1, $2, $3, $4)
RETURNING id, occurred_at
`

type AppendConnectionEventParams struct {
	InstanceID uuid.UUID
	Type       string
	Reason     *string
	Detail     []byte
}

type AppendConnectionEventRow struct {
	ID         int64
	OccurredAt time.Time
}

// The connection trail: what happened to an instance and why.
func (q *Queries) AppendConnectionEvent(ctx context.Context, arg AppendConnectionEventParams) (AppendConnectionEventRow, error) {
	row := q.db.QueryRow(ctx, appendConnectionEvent,
		arg.InstanceID,
		arg.Type,
		arg.Reason,
		arg.Detail,
	)
	var i AppendConnectionEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const deleteConnectionEventsBefore = `-- name: DeleteConnectionEventsBefore :execrows
DELETE FROM connection_events WHERE occurred_at < $1
`

// Retention sweep (FR-037). Runs under an advisory lock so only one worker
// performs it per cycle.
func (q *Queries) DeleteConnectionEventsBefore(ctx context.Context, occurredAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionEventsBefore, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastPairedPhone = `-- name: LastPairedPhone :one
SELECT detail->>'phone_number' AS phone_number
FROM connection_events
WHERE instance_id = $1
  AND type = 'pairing_succeeded'
  AND detail->>'phone_number' IS NOT NULL
ORDER BY id DESC
LIMIT 1
`

// The number this instance was last paired to, read from the trail rather than
// from the instance row: logout clears the identity, so the row cannot answer
// "was this a different number?" on the next pairing (FR-016).
func (q *Queries) LastPairedPhone(ctx context.Context, instanceID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, lastPairedPhone, instanceID)
	var phone_number interface{}
	err := row.Scan(&phone_number)
	return phone_number, err
}

const listConnectionEvents = `-- name: ListConnectionEvents :many
SELECT id, instance_id, type, reason, detail, occurred_at
FROM connection_events
WHERE instance_id = $1
  AND ($2::bigint IS NULL OR id < $2::bigint)
  AND ($3::text[] IS NULL OR type = ANY($3::text[]))
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListConnectionEventsParams struct {
	InstanceID uuid.UUID
	BeforeID   *int64
	Types      []string
	MaxRows    int32
}

// Newest first, keyset paginated on (occurred_at, id). Using the id as the tie
// breaker keeps the cursor stable when several events share a timestamp, which
// is common during a burst of reconnections.
func (q *Queries) ListConnectionEvents(ctx context.Context, arg ListConnectionEventsParams) ([]ConnectionEvent, error) {
	rows, err := q.db.Query(ctx, listConnectionEvents,
		arg.InstanceID,
		arg.BeforeID,
		arg.Types,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectionEvent{}
	for rows.Next() {
		var i ConnectionEvent
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Type,
			&i.Reason,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1) AS acquired
`

// Cheap cross-process mutex for periodic maintenance: whoever gets true runs
// the sweep, everyone else skips it without blocking.
func (q *Queries) TryAdvisoryLock(ctx context.Context, pgTryAdvisoryLock int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, pgTryAdvisoryLock)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}
