// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
)

const countKeysByInstance = `-- name: CountKeysByInstance :one
SELECT count(*) FROM api_keys WHERE instance_id = $1
`

func (q *Queries) CountKeysByInstance(ctx context.Context, instanceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKeysByInstance, instanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstance = `-- name: CreateInstance :one

INSERT INTO instances (id, tenant_id, name, state, created_at, updated_at)
VALUES ($1, $2, $3, 'registered', now(), now())
RETURNING id, tenant_id, name, state, created_at, updated_at
`

type CreateInstanceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
}

// Every statement filters by tenant_id. Scoping in SQL rather than in Go means
// a query can never be reused in a way that reaches another tenant's rows.
func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance, arg.ID, arg.TenantID, arg.Name)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :one
DELETE FROM instances
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, state, created_at, updated_at
`

type DeleteInstanceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

// Returns the row so the caller can audit what disappeared. The API keys of the
// instance go with it through ON DELETE CASCADE (FR-012).
func (q *Queries) DeleteInstance(ctx context.Context, arg DeleteInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, deleteInstance, arg.ID, arg.TenantID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByIDAndTenant = `-- name: GetInstanceByIDAndTenant :one
SELECT id, tenant_id, name, state, created_at, updated_at
FROM instances
WHERE id = $1 AND tenant_id = $2
`

type GetInstanceByIDAndTenantParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetInstanceByIDAndTenant(ctx context.Context, arg GetInstanceByIDAndTenantParams) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceByIDAndTenant, arg.ID, arg.TenantID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstancesByTenant = `-- name: ListInstancesByTenant :many
SELECT id, tenant_id, name, state, created_at, updated_at
FROM instances
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListInstancesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstancesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instance{}
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameInstance = `-- name: RenameInstance :one
UPDATE instances
SET name = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, state, created_at, updated_at
`

type RenameInstanceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) RenameInstance(ctx context.Context, arg RenameInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, renameInstance, arg.ID, arg.TenantID, arg.Name)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
