// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLease = `-- name: AcquireLease :one
UPDATE session_leases
SET worker_id = $2,
    grpc_addr = $3,
    generation = generation + 1,
    heartbeat_at = now(),
    updated_at = now()
WHERE instance_id = $1
  AND desired_state = 'running'
  AND (worker_id IS NULL OR heartbeat_at < now() - $4::interval)
RETURNING generation
`

type AcquireLeaseParams struct {
	InstanceID uuid.UUID
	WorkerID   *string
	GrpcAddr   *string
	Expiry     pgtype.Interval
}

// The atomic heart of exclusive ownership. Concurrent workers all run this
// statement; the WHERE clause means at most one row is updated, so exactly one
// caller gets a RETURNING row and becomes the owner. The generation increments
// on every acquisition and is never reused, which is what lets the worker
// reject commands issued to a previous owner.
func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, acquireLease,
		arg.InstanceID,
		arg.WorkerID,
		arg.GrpcAddr,
		arg.Expiry,
	)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const countLeasesByWorker = `-- name: CountLeasesByWorker :one
SELECT count(*) FROM session_leases WHERE worker_id = $1
`

func (q *Queries) CountLeasesByWorker(ctx context.Context, workerID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countLeasesByWorker, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureLease = `-- name: EnsureLease :exec

INSERT INTO session_leases (instance_id)
VALUES ($1)
ON CONFLICT (instance_id) DO NOTHING
`

// Session ownership. Every statement here exists to uphold one invariant: a
// session is connected in exactly one process at a time (Principle III).
// Creates the lease row on the first connect command. desired_state defaults to
// 'stopped', so the row alone never starts a session — SetDesiredState does.
func (q *Queries) EnsureLease(ctx context.Context, instanceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureLease, instanceID)
	return err
}

const getLease = `-- name: GetLease :one
SELECT instance_id, worker_id, grpc_addr, generation, heartbeat_at, desired_state
FROM session_leases
WHERE instance_id = $1
`

type GetLeaseRow struct {
	InstanceID   uuid.UUID
	WorkerID     *string
	GrpcAddr     *string
	Generation   int64
	HeartbeatAt  *time.Time
	DesiredState string
}

func (q *Queries) GetLease(ctx context.Context, instanceID uuid.UUID) (GetLeaseRow, error) {
	row := q.db.QueryRow(ctx, getLease, instanceID)
	var i GetLeaseRow
	err := row.Scan(
		&i.InstanceID,
		&i.WorkerID,
		&i.GrpcAddr,
		&i.Generation,
		&i.HeartbeatAt,
		&i.DesiredState,
	)
	return i, err
}

const getLeaseOwner = `-- name: GetLeaseOwner :one
SELECT grpc_addr, generation,
       (worker_id IS NOT NULL AND heartbeat_at >= now() - $2::interval) AS is_live
FROM session_leases
WHERE instance_id = $1
`

type GetLeaseOwnerParams struct {
	InstanceID uuid.UUID
	Expiry     pgtype.Interval
}

type GetLeaseOwnerRow struct {
	GrpcAddr   *string
	Generation int64
	IsLive     *bool
}

// Used by the API before dialling: a stale heartbeat means the address in the
// row points at a process that no longer owns the session.
func (q *Queries) GetLeaseOwner(ctx context.Context, arg GetLeaseOwnerParams) (GetLeaseOwnerRow, error) {
	row := q.db.QueryRow(ctx, getLeaseOwner, arg.InstanceID, arg.Expiry)
	var i GetLeaseOwnerRow
	err := row.Scan(&i.GrpcAddr, &i.Generation, &i.IsLive)
	return i, err
}

const heartbeatLeases = `-- name: HeartbeatLeases :many
UPDATE session_leases
SET heartbeat_at = now(), updated_at = now()
WHERE worker_id = $1 AND desired_state = 'running'
RETURNING instance_id, generation
`

type HeartbeatLeasesRow struct {
	InstanceID uuid.UUID
	Generation int64
}

// One statement for every session a worker owns. Returns the instances that
// were actually renewed: anything missing was stolen or stopped, and the worker
// must drop those sessions before another process picks them up.
func (q *Queries) HeartbeatLeases(ctx context.Context, workerID *string) ([]HeartbeatLeasesRow, error) {
	rows, err := q.db.Query(ctx, heartbeatLeases, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatLeasesRow{}
	for rows.Next() {
		var i HeartbeatLeasesRow
		if err := rows.Scan(&i.InstanceID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdoptableLeases = `-- name: ListAdoptableLeases :many
SELECT l.instance_id, l.generation
FROM session_leases l
JOIN instances i ON i.id = l.instance_id
WHERE l.desired_state = 'running'
  AND (l.worker_id IS NULL OR l.heartbeat_at < now() - $1::interval)
  AND (i.last_disconnect_reason IS NULL OR i.last_disconnect_reason <> ALL($2::text[]))
ORDER BY l.updated_at
LIMIT $3
`

type ListAdoptableLeasesParams struct {
	Expiry           pgtype.Interval
	PermanentReasons []string
	MaxRows          int32
}

type ListAdoptableLeasesRow struct {
	InstanceID uuid.UUID
	Generation int64
}

// Free or expired leases that should be running, excluding instances parked on
// a permanent failure: retrying those is pointless until a user command clears
// the reason (FR-029, FR-031).
func (q *Queries) ListAdoptableLeases(ctx context.Context, arg ListAdoptableLeasesParams) ([]ListAdoptableLeasesRow, error) {
	rows, err := q.db.Query(ctx, listAdoptableLeases, arg.Expiry, arg.PermanentReasons, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdoptableLeasesRow{}
	for rows.Next() {
		var i ListAdoptableLeasesRow
		if err := rows.Scan(&i.InstanceID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLease = `-- name: ReleaseLease :exec
UPDATE session_leases
SET worker_id = NULL, grpc_addr = NULL, heartbeat_at = NULL, updated_at = now()
WHERE instance_id = $1 AND worker_id = $2
`

type ReleaseLeaseParams struct {
	InstanceID uuid.UUID
	WorkerID   *string
}

// Graceful handover: clears ownership while preserving generation and
// desired_state, so another worker adopts the session in seconds instead of
// waiting for the expiry.
func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseLease, arg.InstanceID, arg.WorkerID)
	return err
}

const releaseWorkerLeases = `-- name: ReleaseWorkerLeases :exec
UPDATE session_leases
SET worker_id = NULL, grpc_addr = NULL, heartbeat_at = NULL, updated_at = now()
WHERE worker_id = $1
`

func (q *Queries) ReleaseWorkerLeases(ctx context.Context, workerID *string) error {
	_, err := q.db.Exec(ctx, releaseWorkerLeases, workerID)
	return err
}

const setDesiredState = `-- name: SetDesiredState :exec
UPDATE session_leases
SET desired_state = $2, updated_at = now()
WHERE instance_id = $1
`

type SetDesiredStateParams struct {
	InstanceID   uuid.UUID
	DesiredState string
}

func (q *Queries) SetDesiredState(ctx context.Context, arg SetDesiredStateParams) error {
	_, err := q.db.Exec(ctx, setDesiredState, arg.InstanceID, arg.DesiredState)
	return err
}

const setTenantDesiredState = `-- name: SetTenantDesiredState :exec
UPDATE session_leases l
SET desired_state = $2, updated_at = now()
FROM instances i
WHERE l.instance_id = i.id AND i.tenant_id = $1
`

type SetTenantDesiredStateParams struct {
	TenantID     uuid.UUID
	DesiredState string
}

// Bulk projection used when a tenant is suspended or reactivated. The user's
// intent lives on the instance and is untouched here, so reactivation can
// restore exactly what was running before.
func (q *Queries) SetTenantDesiredState(ctx context.Context, arg SetTenantDesiredStateParams) error {
	_, err := q.db.Exec(ctx, setTenantDesiredState, arg.TenantID, arg.DesiredState)
	return err
}
