// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_events.sql

package store

import (
	"context"
	"net/netip"

	uuid "github.com/google/uuid"
)

const countSecurityEventsByType = `-- name: CountSecurityEventsByType :one
SELECT count(*) FROM security_events WHERE event_type = $1
`

// Support query for tests and operational spot checks.
func (q *Queries) CountSecurityEventsByType(ctx context.Context, eventType string) (int64, error) {
	row := q.db.QueryRow(ctx, countSecurityEventsByType, eventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSecurityEvent = `-- name: InsertSecurityEvent :exec
INSERT INTO security_events (
    id, event_type, actor_user_id, target_type, target_id, result, source_ip, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now()
)
`

type InsertSecurityEventParams struct {
	ID          uuid.UUID
	EventType   string
	ActorUserID *uuid.UUID
	TargetType  *string
	TargetID    *uuid.UUID
	Result      string
	SourceIp    *netip.Addr
	Metadata    []byte
}

// Append-only audit record. Written in the same transaction as the action it
// describes whenever that action writes, so the two cannot diverge (FR-021).
func (q *Queries) InsertSecurityEvent(ctx context.Context, arg InsertSecurityEventParams) error {
	_, err := q.db.Exec(ctx, insertSecurityEvent,
		arg.ID,
		arg.EventType,
		arg.ActorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
		arg.SourceIp,
		arg.Metadata,
	)
	return err
}
