// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"
	"time"

	uuid "github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Label      *string
	KeyPrefix  string
	SecretHash []byte
	Status     string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

type ConnectionEvent struct {
	ID         int64
	InstanceID uuid.UUID
	Type       string
	Reason     *string
	Detail     []byte
	OccurredAt time.Time
}

type Instance struct {
	ID                   uuid.UUID
	TenantID             uuid.UUID
	Name                 string
	ConnectionState      string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ConnectionIntent     string
	WaJid                *string
	WaLid                *string
	PhoneNumber          *string
	PushName             *string
	Platform             *string
	BusinessName         *string
	PairedAt             *time.Time
	ConnectedAt          *time.Time
	LastDisconnectAt     *time.Time
	LastDisconnectReason *string
	BanExpiresAt         *time.Time
}

type SecurityEvent struct {
	ID          uuid.UUID
	EventType   string
	ActorUserID *uuid.UUID
	TargetType  *string
	TargetID    *uuid.UUID
	Result      string
	SourceIp    *netip.Addr
	Metadata    []byte
	CreatedAt   time.Time
}

type SessionLease struct {
	InstanceID   uuid.UUID
	WorkerID     *string
	GrpcAddr     *string
	Generation   int64
	HeartbeatAt  *time.Time
	DesiredState string
	UpdatedAt    time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	PasswordHash       string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
