// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"
	"time"

	uuid "github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	InstanceID uuid.UUID
	Label      *string
	KeyPrefix  string
	SecretHash []byte
	Status     string
	CreatedAt  time.Time
	RevokedAt  *time.Time
}

type Instance struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	State     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SecurityEvent struct {
	ID          uuid.UUID
	EventType   string
	ActorUserID *uuid.UUID
	TargetType  *string
	TargetID    *uuid.UUID
	Result      string
	SourceIp    *netip.Addr
	Metadata    []byte
	CreatedAt   time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	PasswordHash       string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
