// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
)

const countTenantCascade = `-- name: CountTenantCascade :one
SELECT
    (SELECT count(*) FROM users u WHERE u.tenant_id = $1) AS user_count,
    (SELECT count(*) FROM instances i WHERE i.tenant_id = $1) AS instance_count,
    (SELECT count(*) FROM api_keys k JOIN instances i2 ON i2.id = k.instance_id WHERE i2.tenant_id = $1) AS api_key_count
`

type CountTenantCascadeRow struct {
	UserCount     int64
	InstanceCount int64
	ApiKeyCount   int64
}

// Counted before deletion so the audit record can state exactly what went with
// the tenant.
func (q *Queries) CountTenantCascade(ctx context.Context, tenantID *uuid.UUID) (CountTenantCascadeRow, error) {
	row := q.db.QueryRow(ctx, countTenantCascade, tenantID)
	var i CountTenantCascadeRow
	err := row.Scan(&i.UserCount, &i.InstanceCount, &i.ApiKeyCount)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, status, created_at, updated_at)
VALUES ($1, $2, 'active', now(), now())
RETURNING id, name, status, created_at, updated_at
`

type CreateTenantParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenantByID = `-- name: DeleteTenantByID :one
DELETE FROM tenants
WHERE id = $1
RETURNING id, name, status, created_at, updated_at
`

// Irreversible. Users, instances and API keys follow through ON DELETE CASCADE
// in this single statement's transaction (FR-007).
func (q *Queries) DeleteTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, deleteTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, status, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, status, created_at, updated_at
FROM tenants
ORDER BY created_at
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_at, updated_at
`

type SetTenantStatusParams struct {
	ID     uuid.UUID
	Status string
}

// Suspension and activation are idempotent: applying the current status again
// succeeds and simply touches updated_at.
func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantName = `-- name: UpdateTenantName :one
UPDATE tenants
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_at, updated_at
`

type UpdateTenantNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantName, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
