// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
UPDATE users
SET failed_login_count = 0, locked_until = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearLoginFailures(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, id)
	return err
}

const countSuperAdmins = `-- name: CountSuperAdmins :one
SELECT count(*) FROM users WHERE role = 'super_admin'
`

func (q *Queries) CountSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, name, email, password_hash, role, tenant_id, must_change_password,
    password_changed_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now(), now(), now()
)
RETURNING id, name, email, role, tenant_id, must_change_password,
          failed_login_count, locked_until, password_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	PasswordHash       string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
}

type CreateUserRow struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.TenantID,
		arg.MustChangePassword,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.TenantID,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantAdminByTenantID = `-- name: GetTenantAdminByTenantID :one
SELECT id, name, email, role, tenant_id, must_change_password,
       failed_login_count, locked_until, password_changed_at, created_at, updated_at
FROM users
WHERE tenant_id = $1 AND role = 'tenant_admin'
ORDER BY created_at
LIMIT 1
`

type GetTenantAdminByTenantIDRow struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetTenantAdminByTenantID(ctx context.Context, tenantID *uuid.UUID) (GetTenantAdminByTenantIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantAdminByTenantID, tenantID)
	var i GetTenantAdminByTenantIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.TenantID,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.name, u.email, u.role, u.tenant_id, u.must_change_password,
       u.failed_login_count, u.locked_until, u.password_changed_at,
       u.created_at, u.updated_at,
       t.status AS tenant_status
FROM users u
LEFT JOIN tenants t ON t.id = u.tenant_id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TenantStatus       *string
}

// Per-request authorisation lookup. Deliberately excludes password_hash: the
// hash must never reach the API layer.
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.TenantID,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantStatus,
	)
	return i, err
}

const getUserCredentialByEmail = `-- name: GetUserCredentialByEmail :one
SELECT u.id, u.name, u.email, u.password_hash, u.role, u.tenant_id,
       u.must_change_password, u.failed_login_count, u.locked_until,
       u.password_changed_at, u.created_at, u.updated_at,
       t.status AS tenant_status
FROM users u
LEFT JOIN tenants t ON t.id = u.tenant_id
WHERE u.email = $1
`

type GetUserCredentialByEmailRow struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	PasswordHash       string
	Role               string
	TenantID           *uuid.UUID
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TenantStatus       *string
}

// The only query that returns password_hash: it serves the login path alone.
// The tenant status rides along so a single indexed lookup decides both
// authentication and the suspension cascade.
func (q *Queries) GetUserCredentialByEmail(ctx context.Context, email string) (GetUserCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByEmail, email)
	var i GetUserCredentialByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.TenantID,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantStatus,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

// Reads the hash for the password-change flow, which must prove the caller
// knows the current password.
func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock(4_182_030_921)
`

// Transaction-scoped advisory lock so concurrently booting replicas cannot each
// create a super-admin. Released automatically when the transaction ends.
func (q *Queries) LockBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockBootstrap)
	return err
}

const registerFailedLogin = `-- name: RegisterFailedLogin :one
UPDATE users
SET failed_login_count = CASE
        WHEN failed_login_count + 1 >= $1::int THEN 0
        ELSE failed_login_count + 1
    END,
    locked_until = CASE
        WHEN failed_login_count + 1 >= $1::int
        THEN now() + make_interval(secs => $2::double precision)
        ELSE locked_until
    END,
    updated_at = now()
WHERE id = $3
RETURNING failed_login_count, locked_until
`

type RegisterFailedLoginParams struct {
	MaxFailures int32
	LockSeconds float64
	ID          uuid.UUID
}

type RegisterFailedLoginRow struct {
	FailedLoginCount int32
	LockedUntil      *time.Time
}

// Durable, transactional lockout (FR-020). On reaching the configured failure
// count the account is locked and the counter resets, so the next window starts
// clean. Unlocking is passive: locked_until simply falls into the past.
func (q *Queries) RegisterFailedLogin(ctx context.Context, arg RegisterFailedLoginParams) (RegisterFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, registerFailedLogin, arg.MaxFailures, arg.LockSeconds, arg.ID)
	var i RegisterFailedLoginRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2,
    must_change_password = $3,
    password_changed_at = now(),
    failed_login_count = 0,
    locked_until = NULL,
    updated_at = now()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID                 uuid.UUID
	PasswordHash       string
	MustChangePassword bool
}

// Sets a new password and stamps password_changed_at, which is what invalidates
// every token issued before this moment (SC-004).
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	return err
}
